spring:
  h2:
    console:
      enabled: true
  mail:
    host: smtp.163.com
    username: zhangxishuo1998@163.com
    password: letter301
    default-encoding: UTF-8

attachment:
  image:
    #  附件上传路径
    directory: attachment/image

server:
  port: 8888
